
# Simple Huckel Calculation


In [321]:

#make a program that calculates effective hamiltonians for a conjugated molecule input


#want to input a .xyz file and output energy values
    #first part is a success

#C-C ~ 1.54 A, C=C ~ 1.34 A
#C-H ~ 1.09 A

In [298]:
import numpy as np
import sympy as sym #might not even need -- only for talking about what you're doing
import pandas as pd
import scipy.spatial as sp
from PyQuante import *

In [318]:
atoms = []
xyz = []
coordinates = []

#input a .xyz file of any conjugated organic molecule here:
    #replace 'benzene.xyz' with desired .xyz file

with open('benzene.xyz', 'r') as input:
    text = input.readlines()
    number_of_atoms = int(text[0].split()[0])
    for i in range(2,len(text)):
        (atom,x,y,z) = text[i].split()
        atoms.append(atom)
        xyz.append([atom,float(x),float(y),float(z)])

        
#replace 'benzene' with name of desired molecule here:
benzene = np.array(xyz)
print(benzene)

#this outputs the xyz coordinates of each atom

[['C' '-1.3551' '2.0086' '-6.1751']
 ['C' '-1.9456' '0.8077' '-5.7669']
 ['C' '-1.7261' '0.3249' '-4.4723']
 ['C' '-0.9162' '1.0429' '-3.5859']
 ['C' '-0.5452' '2.7266' '-5.2886']
 ['C' '-0.3258' '2.2438' '-3.994']
 ['H' '-0.0884' '3.6557' '-5.6044']
 ['H' '-1.5249' '2.3822' '-7.1766']
 ['H' '-0.7464' '0.6693' '-2.5843']
 ['H' '0.3008' '2.7993' '-3.3082']
 ['H' '-2.5721' '0.2523' '-6.4527']
 ['H' '-2.1829' '-0.6041' '-4.1566']]


In [300]:
#need to replace the labels in row 1 with atomic numbers

benzene[benzene == 'C'] = 6
benzene[benzene == 'H'] = 1
print(benzene)

[['6' '-1.3551' '2.0086' '-6.1751']
 ['6' '-1.9456' '0.8077' '-5.7669']
 ['6' '-1.7261' '0.3249' '-4.4723']
 ['6' '-0.9162' '1.0429' '-3.5859']
 ['6' '-0.5452' '2.7266' '-5.2886']
 ['6' '-0.3258' '2.2438' '-3.994']
 ['1' '-0.0884' '3.6557' '-5.6044']
 ['1' '-1.5249' '2.3822' '-7.1766']
 ['1' '-0.7464' '0.6693' '-2.5843']
 ['1' '0.3008' '2.7993' '-3.3082']
 ['1' '-2.5721' '0.2523' '-6.4527']
 ['1' '-2.1829' '-0.6041' '-4.1566']]


In [301]:
from PyQuante import Molecule
from PyQuante.Ints import getbasis, getS

bs='STO-3G'
bfs = getbasis(benzene,basis_data=bs)

#have a problem here -- not formatted exactly right 
    #the problem seems to lie in the xyz coordinates 
    #need to be in parentheses? 

AttributeError: 'numpy.ndarray' object has no attribute 'atno'

In [332]:
#need to create an array of only xyz coordinates (no labels) in order to make connectivity matrix

coord = []

with open('benzene.xyz','r') as input2:
    text = input2.readlines()
    number_of_atoms = int( text[0].split()[0])
    for i in range(2,len(text)):
        (atom,x,y,z)=text[i].split()
        atoms.append(atom)
        coord.append([float(x),float(y),float(z)])
coord=np.array(coord)
print(coord)

#masking gives true/false according to the criteria
masking = coord > 1.2
#print(masking)
coord[masking]

#give an array of the same size with each element=0
connectivity = np.zeros_like(coord)
#print(connectivity)

#show 1 if each element fits the masking criteria 
connectivity[masking]=1
print(connectivity)


[[-1.3551  2.0086 -6.1751]
 [-1.9456  0.8077 -5.7669]
 [-1.7261  0.3249 -4.4723]
 [-0.9162  1.0429 -3.5859]
 [-0.5452  2.7266 -5.2886]
 [-0.3258  2.2438 -3.994 ]
 [-0.0884  3.6557 -5.6044]
 [-1.5249  2.3822 -7.1766]
 [-0.7464  0.6693 -2.5843]
 [ 0.3008  2.7993 -3.3082]
 [-2.5721  0.2523 -6.4527]
 [-2.1829 -0.6041 -4.1566]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [333]:
coord

array([[-1.3551,  2.0086, -6.1751],
       [-1.9456,  0.8077, -5.7669],
       [-1.7261,  0.3249, -4.4723],
       [-0.9162,  1.0429, -3.5859],
       [-0.5452,  2.7266, -5.2886],
       [-0.3258,  2.2438, -3.994 ],
       [-0.0884,  3.6557, -5.6044],
       [-1.5249,  2.3822, -7.1766],
       [-0.7464,  0.6693, -2.5843],
       [ 0.3008,  2.7993, -3.3082],
       [-2.5721,  0.2523, -6.4527],
       [-2.1829, -0.6041, -4.1566]])

In [334]:
# np.split(coord,len(coord))
    # how can i manipulate each of these individual arrays? 


In [316]:
#need to separate each split as its own named array

distance = sp.distance.cdist(C1,C2,'euclidean')
#from huckel @ muammar

NameError: name 'coord1' is not defined

In [295]:
#here you should calculate the distance between each carbon with a for loop:
    #sqrt([xi-x0]**2 + [yi-y0]**2 + [zi-z0]**2)

for i in benzene:
    return 
    
#look at huckel/huckel.py at master * muammar/huckel on GitHub
    #line 125 and down should be helpful

SyntaxError: 'return' outside function (<ipython-input-295-b9ce2dd98e2f>, line 5)

In [296]:
#alpha is equal to the coulomb integral Hii
#beta is equal to the resonance integrals between neighboring atoms


#if i=j then H = alpha
#if i=/=j then H = beta (adjacent atoms)
#if non-adjacent then H = 0

In [297]:
#for the overlap matrices (if you decide to do this)
import scipy.linalg as la

#S_1 = la.inv(P)
#print(S_1)

In [275]:
#with a defined secular equation, solve for eigenvalues and eigenvectors with:

#"evals, evecs = eig(A)" where A is the array
